### ISSUE TITLE
Q: Does it destroy elements not (anymore) in the visible Window?

### ISSUE THREAD

**Issue by hulk66** [Mikescops/vue-virtual-grid#23]
Given you have a very large list of elements (10 of thousands), will it destroy those elements that are no longer visible anymore because the user has scrolled over them already? Otherwise I suppose performance will go down, if there are too many objects in the DOM.

Hope the question is clear & Thanks

**Comment by Mikescops** [comment]
Hello,

Thanks for your question, indeed that's the whole purpose of this module, be able to do virtual scrolling (also known as windowing). 

You can check the live example here: https://vue-virtual-grid.netlify.app/
Open the browser console and see the DOM moving as you scroll :smile:
